### ISSUE TITLE
该脚本在暴力猴下会报错

### ISSUE THREAD

**Issue by rheatin** [Eao-Kind/Self--use-tool#13]
## 你使用的 脚本 是什么版本，nas-tools是什么版本？
> 脚本 版本：
>
> NASTool 版本: 3.2.3
>

## 你遇到什么问题了？

> 在暴力猴下面，似乎没有GM_cookie这个api，报错信息如下
【DEBUG】当前nastools地址：http://192.168.1.20:3000
【DEBUG】当前token:7OC2LZzTALGKtHO5
【Debug】开始获取PT站点信息
PtSiteToNas-tools.user.js:126 
PtSiteToNas-tools.user.js:212 
PtSiteToNas-tools.user.js:216 Uncaught (in promise) ReferenceError: GM_cookie is not defined
    at getData (PtSiteToNas-tools.user.js:216:9)
    at main (PtSiteToNas-tools.user.js:287:22)
    at PtSiteToNas-tools.user.js:130:5
    at PtSiteToNas-tools.user.js:131:3
    at Proxy.VMbsmvq5vfnmt (PtSiteToNas-tools.user.js:312:3)
    at Ut (injected-web.js:1:14233)
    at PtSiteToNas-tools.user.js:1:21
    at async $t (injected.js:1:8152)
    at async injected.js:1:13208

## 你的问题能重现吗？

> 能够重现

**Comment by Eao-Kind** [comment]
是的，暴力猴现在并不支持这个api。
可以修改以下代码。缺点是部分站点的cookie无法获取完整。
// 如果油猴插件是测试版(可获取更多cookie)，保持不变，否则改为"BET"
var tampermonkeyVersion = "BET";
